Sync with microG unofficial installer

diff --git a/zip-content/META-INF/com/google/android/update-binary b/zip-content/META-INF/com/google/android/update-binary
--- a/zip-content/META-INF/com/google/android/update-binary
+++ b/zip-content/META-INF/com/google/android/update-binary
@@ -15,7 +15,7 @@
   GNU General Public License for more details.
 
   You should have received a copy of the GNU General Public License
-  along with this program.  If not, see <http://www.gnu.org/licenses/>.
+  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 LICENSE
 
 ### GLOBAL VARIABLES ###
@@ -28,7 +28,6 @@ export ZIP_PATH=$(dirname "$ZIP_FILE")
 BASE_TMP_PATH='/tmp'
 TMP_PATH='/tmp/custom-setup-a5k'
 
-DEBUG_LOG_ENABLED=0
 MANUAL_TMP_MOUNT=0
 GENER_ERROR=0
 STATUS=1
@@ -39,12 +38,13 @@ export BOOTMODE=false
 
 ### FUNCTIONS ###
 
+DEBUG_LOG_ENABLED=0
 enable_debug_log()
 {
   if [ "$DEBUG_LOG_ENABLED" -eq 1 ]; then return; fi
-  DEBUG_LOG_ENABLED=1
   exec 3>&1 4>&2  # Backup stdout and stderr
   exec 1>>"$ZIP_PATH/debug-a5k.log" 2>&1
+  DEBUG_LOG_ENABLED=1
 }
 
 disable_debug_log()
@@ -52,6 +52,26 @@ disable_debug_log()
   if [ "$DEBUG_LOG_ENABLED" -eq 0 ]; then return; fi
   exec 1>&3 2>&4  # Restore stdout and stderr
   DEBUG_LOG_ENABLED=0
+}
+
+_show_text_on_recovery()
+{
+  echo -e "ui_print $1\nui_print" >> $RECOVERY_PIPE
+}
+
+ui_error()
+{
+  ERROR_CODE=79
+  if test -n "$2"; then ERROR_CODE="$2"; fi
+  >&2 echo "ERROR ${ERROR_CODE}: $1"
+  _show_text_on_recovery "ERROR: $1"
+  exit "${ERROR_CODE}"
+}
+
+ui_warning()
+{
+  >&2 echo "WARNING: $1"
+  _show_text_on_recovery "WARNING: $1"
 }
 
 ui_msg()
@@ -65,14 +85,6 @@ ui_debug()
   echo "$1"
 }
 
-ui_error()
-{
-  #>&2 echo "ERROR: $1"
-  ui_msg "ERROR: $1"
-  test -n "$2" && exit "$2"
-  exit 79
-}
-
 is_mounted()
 {
   case $(mount) in
@@ -81,9 +93,38 @@ is_mounted()
   return 1  # NOT mounted
 }
 
-getprop()
+ensure_system_is_mounted()
 {
-  (test -e '/sbin/getprop' && /sbin/getprop "ro.${1}") || (grep "^ro\.${1}=" '/default.prop' | head -n1 | cut -d '=' -f 2)
+  if ! is_mounted '/system'; then
+    mount '/system'
+    if ! is_mounted '/system'; then ui_error '/system cannot be mounted'; fi
+  fi
+  return 0;  # OK
+}
+
+parse_file()
+{
+  local tmp=$(grep -F "${2}=" "$1" | head -n1 | cut -d '=' -f 2) && echo "$tmp"
+  if test -n "$tmp"; then return 0; fi  # Found
+  return 1  # NOT found
+}
+
+rec_getprop()
+{
+  local prop=''
+  (test -e '/sbin/getprop' && prop=$(/sbin/getprop "ro.$1") && test -n "$prop" && echo "$prop") || (prop=$(parse_file '/default.prop' "ro.$1") && echo "$prop") || (ensure_system_is_mounted && test -e '/system/build.prop' && prop=$(parse_file '/system/build.prop' "ro.$1") && echo "$prop")
+}
+
+get_rec_abilist()
+{
+  local abilist=$(rec_getprop 'product.cpu.abilist')
+  if test -n "$abilist"; then echo "$abilist"; return 0; fi  # Found
+
+  local abi1=$(rec_getprop 'product.cpu.abi')
+  local abi2=$(rec_getprop 'product.cpu.abi2')
+  if test -n "$abi1" || test -n "$abi2"; then echo "$abi1,$abi2"; return 0; fi  # Found
+
+  return 1  # NOT found
 }
 
 is_substring()
@@ -142,14 +183,15 @@ delete_recursive_safe()
   "$BASE_TMP_PATH/busybox" rm -rf "$@" || ui_error "Failed to delete files/folders" 86
 }
 
+# Input related functions
 check_key()
 {
   case "$1" in
-  42)  # Vol +
+  42)   # Vol +
     return 3;;
-  21)  # Vol -
+  21)   # Vol -
     return 2;;
-  143)  # Nothing selected
+  132)  # Error (example: Illegal instruction)
     return 1;;
   *)
     return 0;;
@@ -158,22 +200,31 @@ check_key()
 
 choose_timeout()
 {
-  timeout -t "$1" keycheck
-  check_key "$?"
+  local key_code=1
+  timeout -t "$1" keycheck; key_code="$?"  # Timeout return 127 when it cannot execute the binary
+  if test "$key_code" -eq 143; then
+    ui_msg 'Key code: No key pressed'
+    return 0
+  elif test "$key_code" -eq 127 || test "$key_code" -eq 132; then
+    ui_msg 'WARNING: Key detection failed'
+    return 1
+  fi
+
+  ui_msg "Key code: $key_code"
+  check_key "$key_code"
   return "$?"
 }
 
 choose()
 {
-  local result=1
+  local key_code=1
   ui_msg "QUESTION: $1"
   ui_msg "$2"
   ui_msg "$3"
-  while true; do
-    timeout -t 10 keycheck; result="$?"
-    if [ "$result" -ne 143 ]; then check_key "$result"; return "$?"; fi
-    sleep 0.03
-  done
+  keycheck; key_code="$?"
+  ui_msg "Key code: $key_code"
+  check_key "$key_code"
+  return "$?"
 }
 
 
@@ -187,23 +238,30 @@ if ! is_mounted '/tmp'; then
   MANUAL_TMP_MOUNT=1
   ui_msg 'WARNING: Creating missing /tmp...'
   if [ ! -e '/tmp' ]; then create_dir '/tmp'; fi
-  mount -v -t tmpfs -o rw tmpfs /tmp
+  mount -t tmpfs -o rw tmpfs /tmp
   set_perm 0 2000 0775 '/tmp'
 
   if ! is_mounted '/tmp'; then ui_error '/tmp is NOT mounted'; fi
 fi
 
-ABI_LIST=','$(getprop 'product.cpu.abilist')','$(getprop 'product.cpu.abi')','$(getprop 'product.cpu.abi2')','
+ABI_LIST=",$(get_rec_abilist)," || ui_error "Empty ABI list"
 
-if is_substring ',x86,' "$ABI_LIST"; then
+if is_substring ',x86_64,' "$ABI_LIST"; then
+  ui_debug 'Extracting 64-bit x86 BusyBox...'
+  package_extract_file 'misc/busybox/busybox-x86_64' "$BASE_TMP_PATH/busybox"
+elif is_substring ',x86,' "$ABI_LIST"; then
   ui_debug 'Extracting x86 BusyBox...'
   package_extract_file 'misc/busybox/busybox-x86' "$BASE_TMP_PATH/busybox"
-elif is_substring ',armeabi,' "$ABI_LIST"; then
+elif is_substring ',arm64-v8a,' "$ABI_LIST"; then
+  ui_debug 'Extracting 64-bit ARM BusyBox...'
+  package_extract_file 'misc/busybox/busybox-arm64' "$BASE_TMP_PATH/busybox"
+  package_extract_file 'misc/keycheck/keycheck-arm' "$BASE_TMP_PATH/keycheck"
+elif is_substring ',armeabi,' "$ABI_LIST" || is_substring ',armeabi-v7a,' "$ABI_LIST"; then
   ui_debug 'Extracting ARM BusyBox...'
   package_extract_file 'misc/busybox/busybox-arm' "$BASE_TMP_PATH/busybox"
   package_extract_file 'misc/keycheck/keycheck-arm' "$BASE_TMP_PATH/keycheck"
 else
-  ui_error 'Unsupported CPU'
+  ui_error "Unsupported CPU, ABI list: ${ABI_LIST}"
 fi
 # Give execution rights
 chmod +x "$BASE_TMP_PATH/busybox" || ui_error "chmod failed on '$BASE_TMP_PATH/busybox'" 81  # Needed to make working the "safe" functions
@@ -213,6 +271,8 @@ set_perm_safe 0 0 0755 "$BASE_TMP_PATH/busybox"
 delete_recursive_safe "$TMP_PATH"
 create_dir_safe "$TMP_PATH"
 create_dir_safe "$TMP_PATH/bin"
+
+PREVIOUS_PATH="${PATH}"
 
 # Clean search path so only internal BusyBox applets will be used
 export PATH="$TMP_PATH/bin"
@@ -243,6 +303,9 @@ package_extract_file_safe 'settings.conf' "$TMP_PATH/default-settings.conf"
 . "$TMP_PATH/default-settings.conf"
 test "$DEBUG_LOG" -eq 1 && enable_debug_log  # Enable file logging if needed
 
+# If the debug log was enabled at startup (not in the settings or in the live setup) we cannot allow overriding it from the settings
+if [ "$DEBUG_LOG_ENABLED" -eq 1 ]; then export DEBUG_LOG=1; fi
+
 # Detect boot mode
 (ps | grep zygote | grep -v grep >/dev/null) && BOOTMODE=true
 $BOOTMODE || (ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true)
@@ -252,13 +315,14 @@ if $KEYCHECK_ENABLED && [ "$LIVE_SETUP" -eq 0 ] && [ "${LIVE_SETUP_TIMEOUT}" -ge
   ui_msg '---------------------------------------------------'
   ui_msg 'INFO: Select the VOLUME + key to enable live setup.'
   ui_msg "Waiting input for ${LIVE_SETUP_TIMEOUT} seconds..."
-  choose_timeout "${LIVE_SETUP_TIMEOUT}"; test "$?" -eq 3 && export LIVE_SETUP=1
+  choose_timeout "${LIVE_SETUP_TIMEOUT}"
+  if test "$?" -eq 3; then export LIVE_SETUP=1; fi
 fi
 
 if [ "$LIVE_SETUP" -eq 1 ]; then
   ui_msg 'LIVE SETUP ENABLED!'
   if [ "$DEBUG_LOG" -eq 0 ]; then
-    choose 'Do you want to enable the debug log?' '+) Yes' '-) No'; if [ "$?" -eq 3 ]; then export DEBUG_LOG=1; enable_debug_log; fi
+    choose 'Do you want to enable the debug log?' '+) Yes' '-) No'; if [ "$?" -ne 2 ]; then export DEBUG_LOG=1; enable_debug_log; fi
   fi
 fi
 
@@ -267,11 +331,15 @@ ui_debug 'Starting installation script...'
 "$BASE_TMP_PATH/busybox" bash -c "'$TMP_PATH/install.sh' Preloader '$TMP_PATH'"; STATUS="$?"
 
 test -f "$TMP_PATH/installed" || GENER_ERROR=1
+
+export PATH="${PREVIOUS_PATH}"
 delete_recursive_safe "$TMP_PATH"
+
+#!!! UNSAFE ENVIRONMENT FROM HERE !!!#
 
 test "$DEBUG_LOG" -eq 1 && disable_debug_log  # Disable debug log and restore normal output
 
-test "$MANUAL_TMP_MOUNT" -ne 0 && (umount '/tmp' || ui_error 'Cannot unmount /tmp')
+test "$MANUAL_TMP_MOUNT" -ne 0 && unmount_safe '/tmp'
 
 if test "$STATUS" -ne 0; then ui_error "Installation script failed with error $STATUS" "$STATUS"; fi
 if test "$GENER_ERROR" -ne 0; then ui_error 'Installation failed with an unknown error'; fi
