Sync with microG unofficial installer

diff --git a/.github/workflows/auto-nightly.yml b/.github/workflows/auto-nightly.yml
--- a/.github/workflows/auto-nightly.yml
+++ b/.github/workflows/auto-nightly.yml
@@ -30,7 +30,7 @@ jobs:
         id: "build"
         shell: bash
         run: |
-          ### Building nightly...
+          # Building nightly...
           BUILD_TYPE='oss' '${{ github.workspace }}/build.sh'
       - name: "ZIP info"
         run: |
@@ -54,9 +54,25 @@ jobs:
           printf '%s\n' "::notice::SHA-256: ${ZIP_SHA256:-Missing}"
           printf '%s\n' "::notice::MD5: ${ZIP_MD5:-Missing}"
           : "${ZIP_FOLDER:?}" || exit "${?}"
+      - name: "Do we need to release?"
+        id: "release-decision"
+        shell: bash
+        run: |
+          # Do we need to release?
+          git fetch -q origin
+          CREATE_RELEASE='false'
+          IS_LATEST_COMMIT='false'
+          if test '${{ github.sha }}' = "$(git log -n 1 --pretty='%H' 'origin/main' || :)"; then
+            IS_LATEST_COMMIT='true'
+          fi
+          if test "${IS_LATEST_COMMIT:?}" = 'true' && '${{ steps.build.outputs.ZIP_BUILD_TYPE_SUPPORTED == 'true' && steps.build.outputs.ZIP_IS_ALPHA == 'true' && github.event_name != 'pull_request' }}'; then
+            CREATE_RELEASE='true'
+          fi
+          printf 'CREATE_RELEASE=%s\n' "${CREATE_RELEASE:?}" >> "${GITHUB_OUTPUT?}"
+          printf '%s\n' "${CREATE_RELEASE:?}"
       - name: "Delete previous nightly release"
         uses: actions/github-script@v7
-        if: "${{ github.event_name != 'pull_request' && steps.build.outputs.ZIP_BUILD_TYPE_SUPPORTED == 'true' && steps.build.outputs.ZIP_IS_ALPHA == 'true' }}"
+        if: "${{ steps.release-decision.outputs.CREATE_RELEASE == 'true' }}"
         with:
           retries: 3
           script: |
@@ -66,29 +82,37 @@ jobs:
               repo: context.repo.repo,
               tag: 'nightly'
             }).catch(response => response);
-            if(response.status >= 200 && response.status < 300 && response.data && response.data.id && response.data.tag_name === 'nightly') {
+            if(response && response.status === 404) {
+              // There is no previous nightly release, nothing to do
+            } else if(response && response.status >= 200 && response.status < 300 && response.data && response.data.id && response.data.tag_name === 'nightly') {
               await github.rest.repos.deleteRelease({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 release_id: response.data.id
               });
-              console.log('Previous nightly release deleted: ' + response.data.name + ' (' + response.data.id + ')')
-            } else if(response.status !== 404) {
-              throw response;
+              console.log('Previous nightly release deleted: ' + response.data.name + ' (' + response.data.id + ')');
+            } else {
+              if(response && response.message) console.error('::error::' + response.message);
+              throw new Error('getReleaseByTag failed.');
             }
-            github.rest.git.deleteRef({
+            await github.rest.git.updateRef({
               owner: context.repo.owner,
               repo: context.repo.repo,
-              ref: 'tags/nightly'
+              ref: 'tags/nightly',
+              sha: context.sha,
+              force: true
+            }).then(response => {
+              console.log('Previous nightly tag updated.');
             }).catch(error => {
               if(error.status !== 422 || error.message !== 'Reference does not exist') throw error;
             });
       - name: "Create nightly release"
         uses: softprops/action-gh-release@v2
-        if: "${{ github.event_name != 'pull_request' && steps.build.outputs.ZIP_BUILD_TYPE_SUPPORTED == 'true' && steps.build.outputs.ZIP_IS_ALPHA == 'true' }}"
+        if: "${{ steps.release-decision.outputs.CREATE_RELEASE == 'true' }}"
         with:
           name: "Nightly build"
           tag_name: "nightly"
+          target_commitish: "${{ github.sha }}"
           body: "Latest automatically built ZIP (unstable development snapshot)\n\nSHA-256: ${{ steps.build.outputs.ZIP_SHA256 }}"
           append_body: false
           generate_release_notes: false
